nas:
  hosts:
    nas.tartarus.us:

k3s:
  children: 
    k3s_servers:
    k3s_agents:

k3s_servers:
  hosts:
    # nas.tartarus.us:
    augustus.tartarus.us:
    tiberius.tartarus.us:
    caligula.tartarus.us:
  vars:
    k3s_role: server 

k3s_agents:
  hosts:
    nas.tartarus.us:
    claudius.tartarus.us:
    nero.tartarus.us:
    galba.tartarus.us:
    otho.tartarus.us:
  vars:
    k3s_role: agent 

k8s:
  hosts:
    augustus.tartarus.us:
    tiberius.tartarus.us:
    caligula.tartarus.us:
    claudius.tartarus.us:
    nero.tartarus.us:
    galba.tartarus.us:
    otho.tartarus.us:

romans:
  hosts:
    augustus.tartarus.us:
    tiberius.tartarus.us:
    caligula.tartarus.us:
    claudius.tartarus.us:
    nero.tartarus.us:
    galba.tartarus.us:
    otho.tartarus.us:
