nas:
  hosts:
    nas.tartarus.us

k8s:
  hosts:
    augustus.tartarus.us:
      ansible_ssh_host: 172.16.1.31
    tiberius.tartarus.us:
      ansible_ssh_host: 172.16.1.32
    caligula.tartarus.us:
      ansible_ssh_host: 172.16.1.33
    claudius.tartarus.us:
      ansible_ssh_host: 172.16.1.34
    nero.tartarus.us:
      ansible_ssh_host: 172.16.1.35
    galba.tartarus.us:
      ansible_ssh_host: 172.16.1.36
    otho.tartarus.us:
      ansible_ssh_host: 172.16.1.37