---
bootstrap:
  hosts:
    vitellius.tartarus.us:
      ansible_host: 172.16.1.38
    vespasian.tartarus.us:
      ansible_host: 172.16.1.39
    titus.tartarus.us:
      ansible_host: 172.16.1.40
    domitian.tartarus.us:
      ansible_host: 172.16.1.41
tartarus_hosts:
  children:
    nas:
    romans:
  vars:
    tartarus:
      tools_dir: "/usr/local/tools/bin"

nas:
  hosts:
    nas.tartarus.us:

romans:
  hosts:
    augustus.tartarus.us:
    tiberius.tartarus.us:
    caligula.tartarus.us:
    claudius.tartarus.us:
    nero.tartarus.us:
    galba.tartarus.us:
    otho.tartarus.us:
    vitellius.tartarus.us:
    vespasian.tartarus.us:
    titus.tartarus.us:
    domitian.tartarus.us:

blues:
  hosts:
    augustus.tartarus.us:
    caligula.tartarus.us:
    nero.tartarus.us:
    otho.tartarus.us:
    vespasian.tartarus.us:
    domitian.tartarus.us:
  vars:
    color: blue

greens:
  hosts:
    nas.tartarus.us:
    tiberius.tartarus.us:
    claudius.tartarus.us:
    galba.tartarus.us:
    vitellius.tartarus.us:
    titus.tartarus.us:
  vars:
    color: green

k3s:
  children:
    k3s_servers:
    k3s_agents:

k3s_servers:
  hosts:
    # nas.tartarus.us:
    augustus.tartarus.us:
    tiberius.tartarus.us:
    caligula.tartarus.us:
  vars:
    k3s_role: server

k3s_agents:
  hosts:
    nas.tartarus.us:
    claudius.tartarus.us:
    nero.tartarus.us:
    galba.tartarus.us:
    otho.tartarus.us:
    vitellius.tartarus.us:
    vespasian.tartarus.us:
    titus.tartarus.us:
    domitian.tartarus.us:
  vars:
    k3s_role: agent

k8s:
  hosts:
    augustus.tartarus.us:
    tiberius.tartarus.us:
    caligula.tartarus.us:
    claudius.tartarus.us:
    nero.tartarus.us:
    galba.tartarus.us:
    otho.tartarus.us:

nut_servers:
  hosts:
    augustus.tartarus.us:
  vars:
    nut_role: server

nut_clients:
  hosts:
    tiberius.tartarus.us:
  vars:
    nut_role: client
