---
# tasks file for roles/tartarus.mail
- name: Include secrets
  ansible.builtin.include_vars: secrets.yml

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - msmtp-mta
      - bsd-mailx
    state: present

- name: Configure msmtp-mta
  ansible.builtin.template:
    src: msmtp.conf.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: '0600'
