#SPDX-License-Identifier: MIT-0
---
# tasks file for tartarus_tools
- name: Include vars
  ansible.builtin.include_vars: main.yml

- name: Create a tools destination
  ansible.builtin.file:
    path: /usr/local/tools/bin
    state: directory

- name: Deploy gotify-notify script
  ansible.builtin.template:
    src: gotify-notify.sh
    dest: /usr/local/tools/bin/gotify-notify.sh
    owner: root
    group: root
    mode: '0755'