---
# handlers file for roles/tartarus.zfs
- name: Restart zed
  ansible.builtin.systemd:
    name: zfs-zed
    state: restarted

- name: Restart smartd
  ansible.builtin.systemd:
    name: smartd
    state: restarted
